import Head from "next/head";
import Repo from "../components/Repo";
import Link from "next/link";
import { useContext } from "react";
import { PortfolioContext } from "../context/PortfolioContext";

export default function Home({ data }) {
  const { lenguage, repositories } = useContext(PortfolioContext);

  return (
    <div>
      <Head className="container mx-auto  bg-gray-900">
        <title>Ignacio C.</title>
        <meta charset="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta
          name="viewport"
          content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no"
        />
        <meta name="keywords" content="Keywords" />
        <link rel="manifest" href="/manifest.json" />
        <meta name="description" content="Generated by create next app" />
        <link rel="apple-touch-icon" href="/favicon.ico" />
        <meta name="theme-color" content="#317EFB" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="text-white bg-gray-900 body-font">
        <div className="container px-5 py-24 mx-auto">
          <div className="flex flex-col text-center w-full mb-20">
            <h1 className="sm:text-3xl text-2xl font-medium title-font mb-4 text-white">
              {lenguage === "es" ? "Repositorios" : "Repositories"}
            </h1>
            <div className="flex mx-auto m-6 text-white bg-gray-600 border-0 py-2 px-8 focus:outline-none hover:bg-red-600 rounded text-lg">
              <Link href="https://github.com/ignacioedlp" passHref>
                {lenguage === "es" ? "Ver repositorios" : "See repositories"}
              </Link>
            </div>
          </div>
          <div className="flex flex-wrap -m-2">
            {repositories.map((repo) => (
              <Repo repo={repo} key={repo.id} />
            ))}
          </div>
        </div>
      </section>
    </div>
  );
}
