import Head from "next/head";
import Repo from "../components/Repo";
import Link from "next/link";
import { useContext } from "react";
import { PortfolioContext } from "../context/PortfolioContext";

export async function getStaticProps() {
  try {
    const res = await fetch(
      `https://api.github.com/users/ignacioedlp/repos?per_page=100`
    );
    const data = await res.json();

    return {
      props: {
        data,
      },
    };
  } catch (err) {
    console.log(err);
  }
}

export default function Home({ data }) {
  const { lenguage } = useContext(PortfolioContext);

  return (
    <div>
      <Head classNameName="container mx-auto">
        <title>Ignacio C.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="text-gray-600 body-font">
        <div className="container px-5 py-24 mx-auto">
          <div className="flex flex-col text-center w-full mb-20">
            <h1 className="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">
              Github repositories
            </h1>
            <div className="flex mx-auto m-6 text-white bg-gray-900 border-0 py-2 px-8 focus:outline-none hover:bg-red-600 rounded text-lg">
              <Link href="https://github.com/ignacioedlp" passHref>
                Ver GITHUB
              </Link>
            </div>
          </div>
          <div className="flex flex-wrap -m-2">
            {data.map((repo) => (
              <Repo repo={repo} key={repo.id} />
            ))}
          </div>
        </div>
      </section>
    </div>
  );
}
