import Head from "next/head";
import Profile from "../components/Profile";
import Technologies from "../components/Technologies";
import Proyects from "../components/Proyects";
import Contact from "../components/Contact";
import Resume from "../components/Resume";
import { useContext, useEffect } from "react";
import { PortfolioContext } from "../context/PortfolioContext";

export default function Home() {
  const { lenguage, proyects } = useContext(PortfolioContext);

  useEffect(() => {
    console.log(proyects);
  }, [proyects]);

  return (
    <div>
      <Head className="container mx-auto">
        <title>Ignacio C.</title>
        <meta charset="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta
          name="viewport"
          content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no"
        />
        <meta name="keywords" content="Keywords" />
        <link rel="manifest" href="/manifest.json" />
        <meta name="description" content="Generated by create next app" />
        <link rel="apple-touch-icon" href="/favicon.ico" />
        <meta name="theme-color" content="#317EFB" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Profile lenguage={lenguage}></Profile>
      <Resume lenguage={lenguage}></Resume>
      <Technologies lenguage={lenguage}></Technologies>
      <Proyects lenguage={lenguage} proyects={proyects}></Proyects>
      <Contact lenguage={lenguage}></Contact>
    </div>
  );
}
