import Head from "next/head";
import Hero from "../components_v2/Hero";
import { useContext, useEffect } from "react";
import { PortfolioContext } from "../context/PortfolioContext";
import Navbar from "../components/Navbar";
import AboutMe from "../components_v2/AboutMe";
import Experiencies from "../components_v2/Experiencies";
import Proyects from "../components_v2/Proyects";
import Testimonials from "../components_v2/Testimonials";
import Footer from "../components/Footer";
import 'react-slideshow-image/dist/styles.css';
import "/node_modules/flag-icons/css/flag-icons.min.css";

export default function Home() {
  const { lenguage, proyects, information, skills, testimonials } =
    useContext(PortfolioContext);
  return (
    <div className="bg-seasalt">
      <Head>
        <title>Ignacio C.</title>

        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Nuevos/logo-toxe.png" />
      </Head>

      <div className="md:h-screen  container mx-auto ">
        <Navbar information={information} testimonials={testimonials} />
        <Hero lenguage={lenguage} information={information}></Hero>
      </div>
      <AboutMe lenguage={lenguage} information={information} />
      <Experiencies lenguage={lenguage} information={information} />
      <Proyects lenguage={lenguage} proyects={proyects} />
      {testimonials.lenght == 0 ? <Testimonials lenguage={lenguage} testimonials={testimonials} /> : null}
      <Footer />
    </div>
  );
}
