import Head from "next/head";
import Link from "next/link";
import { React, useContext } from "react";
import Image from "next/image";
import { PortfolioContext } from "../context/PortfolioContext";

export async function getStaticProps() {
  try {
    const res = await fetch(`https://api-portfolio-v2.vercel.app/api/posts`);
    const data = await res.json();

    return {
      props: {
        data,
      },
    };
  } catch (err) {
    console.log(err);
  }
}

export default function Home({ data }) {
  const { lenguage } = useContext(PortfolioContext);

  return (
    <div>
      <Head classNameName="container mx-auto">
        <title>Ignacio C.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="text-gray-400 bg-gray-900 body-font" id="proyects">
        <div className="container px-5 py-24 mx-auto">
          <div className="flex flex-col text-center w-full mb-20">
            <h1 className="sm:text-3xl text-2xl font-medium title-font mb-4 text-white">
              {lenguage === "es" ? "Proyectos" : "Projects"}
            </h1>
          </div>
          <div className="flex flex-wrap sm:-m-4 -mx-4 -mb-10 -mt-4">
            {data.map((repo) => (
              <div key={repo.id} className="lg:w-1/3 sm:w-1/2 p-4 ">
                <div className="flex relative h-64">
                  <Image
                    layout="fill"
                    alt="gallery"
                    className="absolute inset-0 w-full h-full object-cover object-center"
                    src="/proyects/Blog-nextjs.png"
                  />
                  <div className="px-8 py-10 relative z-10 w-full border-4 border-gray-800 bg-gray-900 opacity-0 hover:opacity-100">
                    <h2 className="tracking-widest text-sm title-font font-medium text-red-400 mb-1">
                      {repo.title}
                    </h2>
                    <h1 className="title-font text-lg font-medium text-white mb-3">
                      {repo.content}
                    </h1>
                    <div className="flex mx-auto m-6 text-white bg-red-500 border-0 py-2 px-8 focus:outline-none hover:bg-red-600 rounded text-lg">
                      <Link
                        href="ignacio-cafiero-blogr-nextjs-prisma.vercel.app"
                        passHref
                      >
                        {lenguage === "es" ? "Ver proyecto" : "See project"}
                      </Link>
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>
    </div>
  );
}
